	<script src="<?= base_url('themes/vendor'); ?>/assets/libs/jquery/dist/jquery.min.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/assets/libs/popper.js/dist/umd/popper.min.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/dist/js/app.min.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/dist/js/app.init.horizontal.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/dist/js/app-style-switcher.horizontal.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/assets/extra-libs/sparkline/sparkline.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/dist/js/waves.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/dist/js/sidebarmenu.js"></script>
	<script src="<?= base_url('themes/vendor'); ?>/dist/js/custom.js"></script>
